#!/usr/bin/env python3
"""Build a compact searchable docs/knowledge/INDEX.md.

Python 3.6+ only; no third-party dependencies. Metadata values must stay on one line.
"""
from __future__ import print_function

import io
import os
import re
import sys

REQUIRED = set(["type", "status", "summary", "tags", "paths", "last_verified", "freshness"])
VALID_TYPES = set(["investigation", "decision", "pattern", "runbook"])
VALID_STATUS = set(["current", "provisional", "superseded", "stale"])
VALID_FRESHNESS = set(["stable", "version-sensitive", "volatile"])
SKIP_NAMES = set(["README.md", "INDEX.md"])


def repo_root():
    here = os.path.abspath(__file__)
    # .agents/skills/repo-knowledge/scripts/rebuild_index.py -> repo root
    return os.path.abspath(os.path.join(os.path.dirname(here), "..", "..", "..", ".."))


def read_text(path):
    with io.open(path, "r", encoding="utf-8") as handle:
        return handle.read()


def parse_frontmatter(path):
    text = read_text(path)
    # Accept LF and CRLF after Python newline normalization.
    if not text.startswith("---\n"):
        raise ValueError("frontmatter is missing")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError("frontmatter terminator is missing")
    block = text[4:end]
    data = {}
    for raw in block.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$", line)
        if not match:
            raise ValueError("metadata must use one-line key/value form: {0}".format(raw))
        key = match.group(1)
        value = match.group(2).strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        data[key] = value
    missing = REQUIRED - set(data.keys())
    if missing:
        raise ValueError("missing required metadata: {0}".format(", ".join(sorted(missing))))
    if data["type"] not in VALID_TYPES:
        raise ValueError("invalid type: {0}".format(data["type"]))
    if data["status"] not in VALID_STATUS:
        raise ValueError("invalid status: {0}".format(data["status"]))
    if data["freshness"] not in VALID_FRESHNESS:
        raise ValueError("invalid freshness: {0}".format(data["freshness"]))
    return data


def escape_table(value):
    return value.replace("|", "\\|").replace("\n", " ").strip()


def iter_markdown_files(knowledge):
    for base, dirs, files in os.walk(knowledge):
        dirs[:] = [name for name in dirs if name != "templates"]
        for name in sorted(files):
            if not name.endswith(".md") or name in SKIP_NAMES:
                continue
            yield os.path.join(base, name)


def main():
    root = repo_root()
    knowledge = os.path.join(root, "docs", "knowledge")
    if not os.path.isdir(knowledge):
        print("not found: {0}".format(knowledge), file=sys.stderr)
        return 2

    rows = []
    errors = []
    for path in iter_markdown_files(knowledge):
        try:
            data = parse_frontmatter(path)
            rows.append((path, data))
        except ValueError as exc:
            rel = os.path.relpath(path, root).replace(os.sep, "/")
            errors.append("{0}: {1}".format(rel, exc))

    if errors:
        print("Knowledge metadata validation failed:", file=sys.stderr)
        for error in errors:
            print("- {0}".format(error), file=sys.stderr)
        return 1

    status_order = {"current": 0, "provisional": 1, "superseded": 2, "stale": 3}
    rows.sort(key=lambda item: (
        status_order[item[1]["status"]],
        item[1]["type"],
        item[1]["summary"].lower(),
    ))

    out = [
        "# Repository Knowledge Index",
        "",
        "<!-- AUTO-GENERATED by .agents/skills/repo-knowledge/scripts/rebuild_index.py -->",
        "<!-- 検索を前提とした圧縮カタログ。通常は全文読込せず検索で絞り込む。 -->",
        "",
        "| Status | Type | Summary | Tags | Paths | Freshness | Last verified | Document |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for path, data in rows:
        rel_doc = os.path.relpath(path, knowledge).replace(os.sep, "/")
        out.append(
            "| {status} | {type_} | {summary} | {tags} | {paths} | {freshness} | {last_verified} | [{doc}]({doc}) |".format(
                status=escape_table(data["status"]),
                type_=escape_table(data["type"]),
                summary=escape_table(data["summary"]),
                tags=escape_table(data["tags"]),
                paths=escape_table(data["paths"]),
                freshness=escape_table(data["freshness"]),
                last_verified=escape_table(data["last_verified"]),
                doc=rel_doc,
            )
        )

    index = os.path.join(knowledge, "INDEX.md")
    with io.open(index, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(out) + "\n")
    rel_index = os.path.relpath(index, root).replace(os.sep, "/")
    print("Wrote {0} ({1} entries)".format(rel_index, len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
